/* 
 * Seg API
 *
 * Provide API for Manage Segs
 *
 * OpenAPI spec version: 1.0
 * Contact: vpatel@alliantcreditunion.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = SegApiClient.Client.SwaggerDateConverter;

namespace SegApiClient.Model
{
    /// <summary>
    /// MessageInfo
    /// </summary>
    [DataContract]
    public partial class MessageInfo :  IEquatable<MessageInfo>
    {
        /// <summary>
        /// Defines MessageType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MessageTypeEnum
        {
            
            /// <summary>
            /// Enum Information for value: Information
            /// </summary>
            [EnumMember(Value = "Information")]
            Information = 1,
            
            /// <summary>
            /// Enum Warning for value: Warning
            /// </summary>
            [EnumMember(Value = "Warning")]
            Warning = 2,
            
            /// <summary>
            /// Enum Error for value: Error
            /// </summary>
            [EnumMember(Value = "Error")]
            Error = 3,
            
            /// <summary>
            /// Enum AccountTypeRestriction for value: AccountTypeRestriction
            /// </summary>
            [EnumMember(Value = "AccountTypeRestriction")]
            AccountTypeRestriction = 4,
            
            /// <summary>
            /// Enum Success for value: Success
            /// </summary>
            [EnumMember(Value = "Success")]
            Success = 5,
            
            /// <summary>
            /// Enum Unknown for value: Unknown
            /// </summary>
            [EnumMember(Value = "Unknown")]
            Unknown = 6
        }

        /// <summary>
        /// Gets or Sets MessageType
        /// </summary>
        [DataMember(Name="messageType", EmitDefaultValue=false)]
        public MessageTypeEnum? MessageType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageInfo" /> class.
        /// </summary>
        /// <param name="messageCode">messageCode.</param>
        /// <param name="message">message.</param>
        /// <param name="messageType">messageType.</param>
        /// <param name="messageParams">messageParams.</param>
        public MessageInfo(string messageCode = default(string), string message = default(string), MessageTypeEnum? messageType = default(MessageTypeEnum?), Dictionary<string, string> messageParams = default(Dictionary<string, string>))
        {
            this.MessageCode = messageCode;
            this.Message = message;
            this.MessageType = messageType;
            this.MessageParams = messageParams;
        }
        
        /// <summary>
        /// Gets or Sets MessageCode
        /// </summary>
        [DataMember(Name="messageCode", EmitDefaultValue=false)]
        public string MessageCode { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }


        /// <summary>
        /// Gets or Sets MessageParams
        /// </summary>
        [DataMember(Name="messageParams", EmitDefaultValue=false)]
        public Dictionary<string, string> MessageParams { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessageInfo {\n");
            sb.Append("  MessageCode: ").Append(MessageCode).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  MessageType: ").Append(MessageType).Append("\n");
            sb.Append("  MessageParams: ").Append(MessageParams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MessageInfo);
        }

        /// <summary>
        /// Returns true if MessageInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of MessageInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessageInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MessageCode == input.MessageCode ||
                    (this.MessageCode != null &&
                    this.MessageCode.Equals(input.MessageCode))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.MessageType == input.MessageType ||
                    (this.MessageType != null &&
                    this.MessageType.Equals(input.MessageType))
                ) && 
                (
                    this.MessageParams == input.MessageParams ||
                    this.MessageParams != null &&
                    this.MessageParams.SequenceEqual(input.MessageParams)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MessageCode != null)
                    hashCode = hashCode * 59 + this.MessageCode.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.MessageType != null)
                    hashCode = hashCode * 59 + this.MessageType.GetHashCode();
                if (this.MessageParams != null)
                    hashCode = hashCode * 59 + this.MessageParams.GetHashCode();
                return hashCode;
            }
        }
    }

}
